### ISSUE TITLE
Toplantı

### ISSUE THREAD

**Issue by talhaucarr** [talhaucarr/METUZA#3]
**Bu akşam eğitim öncesi veya sonrasında toplantı yapalım.**

**Comment by muzafferakdogan** [comment]
Ne eğitimi vardı bir de kaçta

25 Mar 2021 Per, saat 16:41 tarihinde talhaucarr ***@***.***>
şunu yazdı:

**Comment by talhaucarr** [comment]
Akşam 9da discordda toplanalım Muzaffer.

**Comment by EnesZulfikaroglu** [comment]
Github eğitimi var 7 de başlıyor. Ondan sonra yaparsak güzel olur.

**Comment by muzafferakdogan** [comment]
Tamamdır Talha. Bu eğitim geçenkinin devamı mı Enes?

25 Mar 2021 Per, saat 16:44 tarihinde EnesZulfikaroglu <
***@***.***> şunu yazdı:

**Comment by EnesZulfikaroglu** [comment]
Hayır, daha detaylı başka bir eğitim. İleri seviye gibi gözüküyor.

**Comment by muzafferakdogan** [comment]
Abanajd tamam kayıt muyut işleri varsa bana bir etkinliği yollasana

25 Mar 2021 Per, saat 17:01 tarihinde EnesZulfikaroglu <
***@***.***> şunu yazdı:

**Comment by talhaucarr** [comment]
Muzaffer lütfen dilimize dikkat edelim. İyi çalışmalar

**Comment by muzafferakdogan** [comment]
Özür dilerim Talha bey whatsapp da zannettim bir an kendimi.

25 Mar 2021 Per, saat 18:34 tarihinde talhaucarr ***@***.***>
şunu yazdı:
